package de.uni_stuttgart.iaas.servicewrapper.opalclus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2019-03-27T13:47:29.517+01:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.uni-stuttgart.de/iaas/serviceWrapper/opalCLUS/", name = "opalCLUS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OpalCLUS {

    @WebMethod(action = "http://www.uni-stuttgart.de/iaas/serviceWrapper/opalCLUS/runOpalCLUS")
    @WebResult(name = "runOpalClusResponse", targetNamespace = "http://www.uni-stuttgart.de/iaas/serviceWrapper/opalCLUS/", partName = "parameters")
    public RunOpalClusResponse runOpalCLUS(
        @WebParam(partName = "parameters", name = "runOpalClus", targetNamespace = "http://www.uni-stuttgart.de/iaas/serviceWrapper/opalCLUS/")
        RunOpalClus parameters
    );
}
