
package de.uni_stuttgart.iaas.servicewrapper.opalclus;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2019-03-27T13:47:29.494+01:00
 * Generated source version: 3.1.12
 * 
 */
public final class OpalCLUS_OpalClusServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.uni-stuttgart.de/iaas/serviceWrapper/opalCLUS/", "OpalClusService");

    private OpalCLUS_OpalClusServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OpalClusService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OpalClusService ss = new OpalClusService(wsdlURL, SERVICE_NAME);
        OpalCLUS port = ss.getOpalClusServicePort();  
        
        {
        System.out.println("Invoking runOpalCLUS...");
        de.uni_stuttgart.iaas.servicewrapper.opalclus.RunOpalClus _runOpalCLUS_parameters = null;
        de.uni_stuttgart.iaas.servicewrapper.opalclus.RunOpalClusResponse _runOpalCLUS__return = port.runOpalCLUS(_runOpalCLUS_parameters);
        System.out.println("runOpalCLUS.result=" + _runOpalCLUS__return);


        }

        System.exit(0);
    }

}
