package de.uni_stuttgart.iaas.servicewrapper.opalclus;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2019-03-27T13:47:29.524+01:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "OpalCLUSCallbackService", 
                  wsdlLocation = "file:/D:/TraDE/GitHub/trade-opalCLUS-wrapper/src/main/resources/opalCLUS.wsdl",
                  targetNamespace = "http://www.uni-stuttgart.de/iaas/serviceWrapper/opalCLUS/") 
public class OpalCLUSCallbackService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.uni-stuttgart.de/iaas/serviceWrapper/opalCLUS/", "OpalCLUSCallbackService");
    public final static QName OpalCLUSCallbackServicePort = new QName("http://www.uni-stuttgart.de/iaas/serviceWrapper/opalCLUS/", "OpalCLUSCallbackServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/TraDE/GitHub/trade-opalCLUS-wrapper/src/main/resources/opalCLUS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OpalCLUSCallbackService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/TraDE/GitHub/trade-opalCLUS-wrapper/src/main/resources/opalCLUS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OpalCLUSCallbackService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OpalCLUSCallbackService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpalCLUSCallbackService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OpalCLUSCallbackService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OpalCLUSCallbackService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OpalCLUSCallbackService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OpalCLUSCallback
     */
    @WebEndpoint(name = "OpalCLUSCallbackServicePort")
    public OpalCLUSCallback getOpalCLUSCallbackServicePort() {
        return super.getPort(OpalCLUSCallbackServicePort, OpalCLUSCallback.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpalCLUSCallback
     */
    @WebEndpoint(name = "OpalCLUSCallbackServicePort")
    public OpalCLUSCallback getOpalCLUSCallbackServicePort(WebServiceFeature... features) {
        return super.getPort(OpalCLUSCallbackServicePort, OpalCLUSCallback.class, features);
    }

}
